### ISSUE TITLE
MUAD Dataset instead of InfraParis Dataset linked

### ISSUE THREAD

**Issue by JensBayer** [ENSTA-U2IS/infraParis#2]
Hey there,
thanks for sharing the dataset. It seems, that the link from the Google forms redirects you to the Google Drive download page for the MUAD Dataset instead of the InfraParis Dataset. Could you fix this?

**Comment by giannifranchi** [comment]
Hello JensBayer, I do not know what was the issue. 
To be honest I had the same issue, and I have deleted the cookies of my computer and now it works. I have deleted your google form application. Please re do it. If there is an issue please warn me.
