### ISSUE TITLE
No dataset found

### ISSUE THREAD

**Issue by nandini211995** [ENSTA-U2IS/infraParis#4]
Dear authors,

Where is the dataset link? Is there upload any drive link or any other link? How should download?

**Comment by belkhir-nacim** [comment]
Dear @nandini211995 ,
Thank you for your interest in our dataset. The dataset is available upon a form request [[link here]](https://docs.google.com/forms/d/e/1FAIpQLSe2kzVsfD3657AlppTInV8Yp1ptWEic6_Nl5VisNoHu9nTYvQ/viewform)
You also can find the link to the form in the website page.
![image](https://github.com/ENSTA-U2IS-AI/infraParis/assets/4836103/1bd9a715-0b51-452a-af36-ac2d38f42ba3)
Once we review your request we will give you the link to download it.

We will update the page in such way to make to improve the visibility of the link.

**Comment by belkhir-nacim** [comment]
@nandini211995 Does my answer could help you? don't hesitate to reopen this issue if you still have some issue accessing the data

**Comment by ozgurovic** [comment]
Hello, will this link be active: https://ensta-u2is.github.io/infraParis/
and will there be tracking information for object detection?
