### ISSUE TITLE
IR images blank 

### ISSUE THREAD

**Issue by chogan99** [ENSTA-U2IS/infraParis#6]
IR images seem to be blank upon downloading dataset 
![t_1621534069_8](https://github.com/user-attachments/assets/1b7d07e5-d5f8-46d6-aac6-dfd213222a34)

**Comment by belkhir-nacim** [comment]
Hello, the IR images are encoded on 16bits.They are directly readable with skimage or PIL.

**Comment by chogan99** [comment]
Thank you
